### ISSUE TITLE
Fit on one dataset, fill from another. 

### ISSUE THREAD

**Issue by PolarBean** [ScionKim/FaissImputer#1]
Background:
I have two datasets, one is full of nan values. I have another complete dataset with no nan values. The complete dataset is much higher quality in many other ways so I would like to find the nearest neighbour in the complete dataset for every row in the incomplete dataset. 
Question:
Is it possible using your library to fit on dataset and fill on another (also ideally return the index of the matched row). 
This is a great library, thank you in advance.

**Comment by ScionKim** [comment]
I apologize for the delayed response as I am currently preparing to travel abroad to visit my family for the end of the year. I've created a simple example, but I'm not sure if it's exactly what you're looking for.

```python
# incomplete dataset
X_incomplete = np.array([[1.0, np.nan, 3.0], [4.0, 4.0, np.nan], [np.nan, 2.0, 4.0]])

# complete dataset
X_complete = np.array([[1.0, 2.0, 3.0], [4.0, 4.0, 3.0], [3.0, 2.0, 4.0]])

# Initialize FaissImputer
imputer = FaissImputer()

# Fit on both incomplete and complete datasets
imputer.fit(np.vstack((X_incomplete, X_complete)))

# Find neighbors for incomplete dataset
X_completed = imputer.transform(X_incomplete)

# Get neighbor indices
nearest_neighbors = imputer.index_.search(X_completed, 1)[1]

# Filter to return only the first neighbor
nearest_neighbors = nearest_neighbors[:, 0]

print(nearest_neighbors)
-> [0 1 2]
```

I could consider adding your suggestion as a new feature, but it seems feasible to use it in the way described above. This is just a quick implementation, so there are many aspects that need refining. I'll continue to make improvements going forward.

**Comment by PolarBean** [comment]
Thank you so much for taking the time to answer me. This answers my question.
